oj_server:oj_server.cc
	g++ -o $@ $^ -std=c++11 -lpthread -ljsoncpp -lctemplate
.PHNOY:clean
clean:
	rm -f oj_server




# g++ -o $@ $^ -std=c++11 -ljsoncpp -lpthread -L /home/yzl/ThirdPartLibForCpp/el7.x86_64/third_part/lib -lctemplate -g -I /home/yzl/ThirdPartLibForCpp/el7.x86_64/third_part/include
